CREATE TABLE IF NOT EXISTS projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectid INTEGER REFERENCES projects(id)

);

INSERT INTO projects(name,priority, description, deliverydate)
    VALUES('Make a Web App', 1 , 'Using Javascript', '2019-07-19' );

INSERT INTO projects(name,priority, description, deliverydate)
    VALUES('Make Mobile App', 1 , 'Using React Native', '2019-08-10' );

INSERT INTO projects(name,priority, description, deliverydate)
    VALUES('Make static Web', 1 , 'Using Bootstrap', '2019-10-15' );


INSERT INTO tasks(name,done, projectid)
    VALUES('Download Vuejs', false ,1);

INSERT INTO tasks(name,done, projectid)
    VALUES('Create UI WEB', false ,1);

INSERT INTO tasks(name,done, projectid)
    VALUES('Download React Native', false ,2);
    
INSERT INTO tasks(name,done, projectid)
    VALUES('Design UI', false ,2);

